<div class="row">
    <div class="col-md-4">
        <?php
        $form->setAttribute('action', $this->url('storage'));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        $storage = $form->get('storage');
        ?>
        <?= $this->form()->openTag($form) ?>
        <fieldset>
            <legend><h2>Add new storage</h2></legend>
            <div class="form-group">
                <label for="name">Storage Name</label>
                <?= $this->formText($storage->get('storage_name')) ?>
                <?= $this->formElementErrors()->render($storage->get('storage_name'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <label for="slug">Storage Url</label>
                <?= $this->formText($storage->get('storage_url')) ?>
                <?= $this->formElementErrors()->render($storage->get('storage_url'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <?= $this->formButton($form->get('submit'), 'Create') ?>
            </div>

        </fieldset>
        <?php
        echo $this->formHidden($storage->get('storage_id'));
        echo $this->formHidden($form->get('storage_csrf'));
        echo $this->form()->closeTag()
        ?>
    </div>
    <div class = "col-md-8">
        <legend><h2>Storage</h2></legend>
        <?php
        if (count($this->paginator)):
            ?>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $redirect_url = urlencode($this->serverUrl(true));
                    foreach ($this->paginator as $item):
                        ?>
                        <tr>
                            <th scope="row"><?= $item->getStorageId() ?></th>
                            <td><?= $item->getStorageName() ?></td>
                            <td>
                                <a href="<?= $this->url('storage/edit', ['id' => $item->getStorageId()]) ?>" title="Edit"><i class="fa fa-edit fa-fw"></i> Edit</a>
                                <a href="<?= $this->url('storage/delete', ['id' => $item->getStorageId()], ['query' => ['redirect_url' => $redirect_url]]) ?>" class="text-danger" title="Delete"><i class="fa fa-trash-o fa-fw"></i> Delete</a>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                    ?>

                </tbody>
            </table>
            <?php
            echo $this->paginationControl(
                    $this->paginator, 'Sliding', 'partial/bootstrap-paginator', ['route' => 'storage/paging']
            );
        else:
            ?>
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> Storage is empty.
            </div>
        <?php
        endif;
        ?>
    </div>
</div>