<?php
$this->headTitle('Sign In');
echo $this->partial('layout/header');
?>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $form->prepare();
                    ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <fieldset>
                        <div class="form-group">
                            <?php echo $this->formEmail($form->get('email')) ?>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formPassword($form->get('password')); ?>
                        </div>
                        <div class="checkbox">
                            <label>
                                <input name="remember" type="checkbox" value="1">Remember Me
                            </label>
                        </div>
                        <!-- Change this to a button or input when using this as a form -->
                        <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                    </fieldset>
                    <?php
                    echo $this->formHidden($form->get('login_csrf'));
                    echo $this->form()->closeTag()
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->partial('layout/footer');
