<div class="row">
    <div class="col-md-3">
        <?php
        $form->setAttribute('action', $this->url('song'));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        $song = $form->get('song');
        ?>
        <?= $this->form()->openTag($form) ?>
        <BR/>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Filter</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <?= $this->formText($song->get('song_name')) ?>
                        <?= $this->formElementErrors()->render($song->get('song_name'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="form-group">
                        <label for="category_id">Category</label>
                        <?= $this->formSelect($song->get('category_id')) ?>
                        <?= $this->formElementErrors()->render($song->get('category_id'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="form-group">
                        <label for="song_status">Status</label>
                        <?= $this->formSelect($song->get('song_status')) ?>
                        <?= $this->formElementErrors()->render($song->get('song_status'), ['class' => 'help-block']) ?>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="form-group">
                    <?= $this->formButton($form->get('submit'), 'Submit') ?>
                </div>
            </div>
        </div>

        <?php
        echo $this->formHidden($form->get('song_csrf'));
        echo $this->formHidden($song->get('song_id'));
        echo $this->form()->closeTag()
        ?>
    </div>
    <div class="col-md-9">
        <legend><h2>Song</h2></legend>
        <?php
        if (count($this->paginator)):
            ?>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $redirect_url = urlencode($this->serverUrl(true));
                    foreach ($this->paginator as $item):
                        ?>
                        <tr>
                            <th scope="row"><?= $item->getSongId() ?></th>
                            <td><?= $item->getSongName() ?></td>
                            <td>
                                <a href="<?= $this->url('song/edit', ['id' => $item->getSongId()]) ?>" title="Edit"><i class="fa fa-edit fa-fw"></i> Edit</a>
                                <a href="<?= $this->url('song/delete', ['id' => $item->getSongId()], ['query' => ['redirect_url' => $redirect_url]]) ?>" class="text-danger" title="Delete"><i class="fa fa-trash-o fa-fw"></i> Delete</a>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                    ?>

                </tbody>
            </table>
            <?php
            echo $this->paginationControl(
                    $this->paginator, 'Sliding', 'partial/bootstrap-paginator', ['route' => 'song/paging']
            );
        else:
            ?>
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> Song is empty.
            </div>
        <?php
        endif;
        if (isset($_COOKIE['song'])):
            ?>
            <a href="<?= $this->url('song', [], ['query' => ['clearResult' => 'yes']]) ?>" class="clearfix text-danger"><i class="fa fa-fw fa-trash-o"></i>Xóa kết quả hiển thị ở chế độ lọc</a>
            <?php
        endif;
        ?>
    </div>
</div>