<div class="row">
    <div class="col-md-4">
        <?php
        $form->setAttribute('action', $this->url('category'));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        $category = $form->get('category');
        ?>
        <?= $this->form()->openTag($form) ?>
        <fieldset>
            <legend><h2>Add new category</h2></legend>
            <div class="form-group">
                <label for="name">Category Name</label>
                <?= $this->formText($category->get('category_name')) ?>
                <?= $this->formElementErrors()->render($category->get('category_name'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <label for="slug">Category Slug</label>
                <?= $this->formText($category->get('category_slug')) ?>
                <?= $this->formElementErrors()->render($category->get('category_slug'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <label for="slug">Category Description</label>
                <?= $this->formTextarea($category->get('category_description')) ?>
                <?= $this->formElementErrors()->render($category->get('category_description'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <?= $this->formButton($form->get('submit'), 'Create') ?>
            </div>

        </fieldset>
        <?php
        echo $this->formHidden($category->get('category_id'));
        echo $this->formHidden($form->get('category_csrf'));
        echo $this->form()->closeTag()
        ?>
    </div>
    <div class = "col-md-8">
        <legend><h2>Category</h2></legend>
        <?php
        if (count($this->paginator)):
            ?>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $redirect_url = urlencode($this->serverUrl(true));
                    foreach ($this->paginator as $item):
                        ?>
                        <tr>
                            <th scope="row"><?= $item->getCategoryId() ?></th>
                            <td><?= $item->getCategoryName() ?></td>
                            <td>
                                <a href="<?= $this->url('category/edit', ['id' => $item->getCategoryId()]) ?>" title="Edit"><i class="fa fa-edit fa-fw"></i> Edit</a> 
                                <a href="<?= $this->url('category/delete', ['id' => $item->getCategoryId()], ['query' => ['redirect_url' => $redirect_url]]) ?>" class="text-danger" title="Delete"><i class="fa fa-trash-o fa-fw"></i> Delete</a>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                    ?>

                </tbody>
            </table>
            <?php
            echo $this->paginationControl(
                    $this->paginator, 'Sliding', 'partial/bootstrap-paginator', ['route' => 'category/paging']
            );
        else:
            ?>
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> Category is empty.
            </div>
        <?php
        endif;
        ?>
    </div>
</div>