<?php
$title = 'Add new user';
$this->headTitle($title);
$form->setAttribute('action', $this->url('user/add', ['action' => 'index']));
$form->setAttribute('class', 'form-horizontal');
$user = $form->get('user');
$form->prepare();
?>
<div class="row">
    <style type="text/css">
        .help-block{
            color:#E86262 !important;
        }
    </style>
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <!-- Add User Form -->
        <legend><h1><?= $this->escapeHtml($title) ?></h1></legend>

        <?php
        if ($this->userExists) {
            ?>
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Error!</strong> <?= $this->userExists; ?>
            </div>
            <?php
        }
        ?>
        <div class="form-group">
            <label class="col-md-4 control-label" for="name">Username</label>
            <div class="col-md-4">
                <?= $this->formText($user->get('user_name')) ?>
                <?= $this->formElementErrors()->render($user->get('user_name'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-4">
                <?= $this->formPassword($user->get('user_password')) ?>
                <?= $this->formElementErrors()->render($user->get('user_password'), ['class' => 'help-block']) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="re-password">Re-type Password</label>
            <div class="col-md-4">
                <?= $this->formPassword($form->get('re-password')) ?>
                <?= $this->formElementErrors()->render($form->get('re-password'), ['class' => 'help-block']) ?>
            </div>
        </div>
        <hr/>
        <div class="form-group">
            <label class="col-md-4 control-label" for="first-name">Your Name</label>
            <div class="col-md-2">
                <?= $this->formText($user->get('user_first_name')) ?>
            </div>
            <div class="col-md-2">
                <?= $this->formText($user->get('user_last_name')) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email</label>
            <div class="col-md-4">
                <?= $this->formEmail($user->get('user_email')) ?>
                <?= $this->formElementErrors()->render($user->get('user_email'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="role">Role</label>
            <div class="col-md-4">
                <?= $this->formSelect($user->get('user_role')) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="role"></label>
            <div class="col-md-4">
                <?= $this->formButton($form->get('submit'), 'Create') ?>
            </div>
        </div>

    </fieldset>
    <?php
    echo $this->formHidden($user->get('user_id'));
    echo $this->formHidden($form->get('user_csrf'));
    echo $this->form()->closeTag()
    ?>
</div>