<div class="row">
    <div class="col-md-4">
        <?php
        $form->setAttribute('action', $this->url('collection'));
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        $collection = $form->get('collection');
        ?>
        <?= $this->form()->openTag($form) ?>
        <fieldset>
            <legend><h2>Add new collection</h2></legend>
            <div class="form-group">
                <label for="name">Collection Name</label>
                <?= $this->formText($collection->get('collection_name')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_name'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <label for="slug">Collection Slug</label>
                <?= $this->formText($collection->get('collection_slug')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_slug'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <label for="slug">Collection Description</label>
                <?= $this->formTextarea($collection->get('collection_description')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_description'), ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <?= $this->formButton($form->get('submit'), 'Create') ?>
            </div>

        </fieldset>
        <?php
        echo $this->formHidden($collection->get('collection_id'));
        echo $this->formHidden($form->get('collection_csrf'));
        echo $this->form()->closeTag()
        ?>
    </div>
    <div class = "col-md-8">
        <legend><h2>Collection</h2></legend>
        <?php
        if (count($this->paginator)):
            ?>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $redirect_url = urlencode($this->serverUrl(true));
                    foreach ($this->paginator as $item):
                        ?>
                        <tr>
                            <th scope="row"><?= $item->getCollectionId() ?></th>
                            <td><?= $item->getCollectionName() ?></td>
                            <td>
                                <a href="<?= $this->url('collection/edit', ['id' => $item->getCollectionId()]) ?>" title="Edit"><i class="fa fa-edit fa-fw"></i> Edit</a>
                                <a href="<?= $this->url('collection/delete', ['id' => $item->getCollectionId()], ['query' => ['redirect_url' => $redirect_url]]) ?>" class="text-danger" title="Delete"><i class="fa fa-trash-o fa-fw"></i> Delete</a>
                            </td>
                        </tr>
                        <?php
                    endforeach;
                    ?>

                </tbody>
            </table>
            <?php
            echo $this->paginationControl(
                    $this->paginator, 'Sliding', 'partial/bootstrap-paginator', ['route' => 'collection/paging']
            );
        else:
            ?>
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> Collection is empty.
            </div>
        <?php
        endif;
        ?>
    </div>
</div>