<?php
$title = 'Edit collection';
$this->headTitle($title);
$form->setAttribute('action', $this->url('collection/edit', ['id' => $id]));
$form->setAttribute('class', 'form-horizontal');
$collection = $form->get('collection');
$form->prepare();
$flashMessengerPlugin = $this->flashMessenger()->getPluginFlashMessenger();
?>
<div class="row">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <legend><h2><?= $this->escapeHtml($title) ?></h2></legend>
        <?php
        // hiển thị thông báo có lỗi
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('error', array('alert', 'alert-danger'));
        $flashMessengerPlugin->clearCurrentMessages('error');
        ?>
        <?php
        // hiển thị thông báo thành công
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Success!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('success', array('alert', 'alert-success'));
        $flashMessengerPlugin->clearCurrentMessages('success');
        ?>
        <div class="form-group">
            <label class="col-md-4 control-label" for="name">Collection Name</label>
            <div class="col-md-4">
                <?= $this->formText($collection->get('collection_name')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_name'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="slug">Collection Slug</label>
            <div class="col-md-4">
                <?= $this->formText($collection->get('collection_slug')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_slug'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="slug">Collection Description</label>
            <div class="col-md-4">
                <?= $this->formTextarea($collection->get('collection_description')) ?>
                <?= $this->formElementErrors()->render($collection->get('collection_description'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="role"></label>
            <div class="col-md-4">
                <?= $this->formButton($form->get('submit'), 'Save') ?>
                <?= $this->formReset($form->get('reset')); ?>
                <a href="<?= $this->url('collection/delete', ['id' => $id], ['query' => ['redirect_url' => \urlencode($this->serverUrl(true))]]) ?>" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-o"></i> Delete</a>
            </div>
        </div>

    </fieldset>
    <?php
    echo $this->formHidden($collection->get('collection_id'));
    echo $this->formHidden($form->get('collection_csrf'));
    echo $this->form()->closeTag()
    ?>
</div>