<?php
$title = 'Edit song';
$this->headTitle($title);
$form->setAttribute('action', $this->url('song/edit', ['id' => $id]));
$form->setAttribute('class', 'form-horizontal');
$song = $form->get('song');
$form->prepare();
$flashMessengerPlugin = $this->flashMessenger()->getPluginFlashMessenger();
?>
<div class="row">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <legend><h2><?= $title ?></h2></legend>
        <?php
        // hiển thị thông báo có lỗi
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('error', array('alert', 'alert-danger'));
        $flashMessengerPlugin->clearCurrentMessages('error');
        ?>
        <?php
        // hiển thị thông báo thành công
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Success!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('success', array('alert', 'alert-success'));
        $flashMessengerPlugin->clearCurrentMessages('success');
        ?>
        <div class="col-md-8">
            <div style="padding: 0 15px 0 15px">
                <div class="form-group">
                    <?= $this->formText($song->get('song_name')) ?>
                    <?= $this->formElementErrors()->render($song->get('song_name'), ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                    <?= $this->formCKEditor($song->get('song_lyric')) ?>
                    <?= $this->formElementErrors()->render($song->get('song_lyric'), ['class' => 'help-block']) ?>
                </div>
            </div>
            <!--Begin section Mp3-->
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-music fa-cogs"></i> Mp3</div>
                <div class="panel-body">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="title">Storage</label>
                            <?= $this->formSelect($song->get('storage_id')) ?>
                            <?= $this->formElementErrors()->render($song->get('storage_id'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <label for="title">Path</label>
                            <?= $this->formText($song->get('storage_path')) ?>
                            <?= $this->formElementErrors()->render($song->get('storage_path'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                </div>
            </div>
            <!--End section Mp3-->

            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-cogs"></i> SEO Setting</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="title">Title</label>
                        <div class="col-md-9">
                            <?= $this->formText($song->get('title')) ?>
                            <?= $this->formElementErrors()->render($song->get('title'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="description">Meta Description</label>
                        <div class="col-md-9">
                            <?= $this->formTextarea($song->get('meta_description')) ?>
                            <?= $this->formElementErrors()->render($song->get('meta_description'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="keywords">Meta Keywords</label>
                        <div class="col-md-9">
                            <?= $this->formText($song->get('meta_keywords')) ?>
                            <?= $this->formElementErrors()->render($song->get('meta_keywords'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="keywords">Meta Robots</label>
                        <div class="col-md-9">
                            <?= $this->formSelect($song->get('meta_robots')) ?>
                            <?= $this->formElementErrors()->render($song->get('meta_robots'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading"><i class="fa fa-fw fa-cogs"></i> General Setting</div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Collections</label>
                            <div class="checkbox">
                                <?= $this->formMultiCheckbox($song->get('collections')) ?>
                            </div>
                            <?= $this->formElementErrors()->render($song->get('collections'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Slug</label>
                            <?= $this->formText($song->get('song_slug')) ?>
                            <?= $this->formElementErrors()->render($song->get('song_slug'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Category</label>
                            <?= $this->formSelect($song->get('category_id')) ?>
                            <?= $this->formElementErrors()->render($song->get('category_id'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Status</label>
                            <?= $this->formSelect($song->get('song_status')) ?>
                            <?= $this->formElementErrors()->render($song->get('song_status'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <?= $this->formButton($form->get('submit'), 'Save') ?>
                    <a href="<?= $this->url('song/delete', ['id' => $id], ['query' => ['redirect_url' => \urlencode($this->serverUrl(true))]]) ?>" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-o"></i> Delete</a>
                </div>
            </div>
        </div>
    </fieldset>
    <?php
//   / echo $this->formHidden($song->get('song_id'));
    echo $this->formHidden($form->get('song_csrf'));
    echo $this->formHidden($song->get('user_id'));
    echo $this->formHidden($song->get('song_id'));
    echo $this->form()->closeTag()
    ?>
</div>