<?php
$title = 'Edit storage';
$this->headTitle($title);
$form->setAttribute('action', $this->url('storage/edit', ['id' => $id]));
$form->setAttribute('class', 'form-horizontal');
$storage = $form->get('storage');
$form->prepare();
$flashMessengerPlugin = $this->flashMessenger()->getPluginFlashMessenger();
?>
<div class="row">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <legend><h2><?= $this->escapeHtml($title) ?></h2></legend>
        <?php
        // hiển thị thông báo có lỗi
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('error', array('alert', 'alert-danger'));
        $flashMessengerPlugin->clearCurrentMessages('error');
        ?>
        <?php
        // hiển thị thông báo thành công
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Success!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('success', array('alert', 'alert-success'));
        $flashMessengerPlugin->clearCurrentMessages('success');
        ?>
        <div class="form-group">
            <label class="col-md-4 control-label" for="name">Storage Name</label>
            <div class="col-md-4">
                <?= $this->formText($storage->get('storage_name')) ?>
                <?= $this->formElementErrors()->render($storage->get('storage_name'), ['class' => 'help-block']) ?>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="url">Storage Url</label>
            <div class="col-md-4">
                <?= $this->formText($storage->get('storage_url')) ?>
                <?= $this->formElementErrors()->render($storage->get('storage_url'), ['class' => 'help-block']) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label" for="role"></label>
            <div class="col-md-4">
                <?= $this->formButton($form->get('submit'), 'Save') ?>
                <?= $this->formReset($form->get('reset')); ?>
                <a href="<?= $this->url('storage/delete', ['id' => $id], ['query' => ['redirect_url' => \urlencode($this->serverUrl(true))]]) ?>" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-o"></i> Delete</a>
            </div>
        </div>

    </fieldset>
    <?php
    echo $this->formHidden($storage->get('storage_id'));
    echo $this->formHidden($form->get('storage_csrf'));
    echo $this->form()->closeTag()
    ?>
</div>