<?php
$title = 'Edit page';
$this->headTitle($title);
$form->setAttribute('action', $this->url('page/edit', ['id' => $id]));
$form->setAttribute('class', 'form-horizontal');
$page = $form->get('page');
$form->prepare();
$flashMessengerPlugin = $this->flashMessenger()->getPluginFlashMessenger();
?>
<div class="row">
    <?= $this->form()->openTag($form) ?>
    <fieldset>
        <legend><h2><?= $title ?></h2></legend>
        <?php
        // hiển thị thông báo có lỗi
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Error!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('error', array('alert', 'alert-danger'));
        $flashMessengerPlugin->clearCurrentMessages('error');
        ?>
        <?php
        // hiển thị thông báo thành công
        echo $this->flashMessenger()
                ->setMessageOpenFormat('<div %s><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a><strong>Success!</strong> ')
                ->setMessageSeparatorString('')
                ->setMessageCloseString('</div>')
                ->renderCurrent('success', array('alert', 'alert-success'));
        $flashMessengerPlugin->clearCurrentMessages('success');
        ?>
        <div class="col-md-8">
            <div style="padding: 0 15px 0 15px">
                <div class="form-group">
                    <?= $this->formText($page->get('page_name')) ?>
                    <?= $this->formElementErrors()->render($page->get('page_name'), ['class' => 'help-block']) ?>
                </div>
                <div class="form-group">
                    <?= $this->formCKEditor($page->get('page_content')) ?>
                    <?= $this->formElementErrors()->render($page->get('page_content'), ['class' => 'help-block']) ?>
                </div>
            </div>


            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-fw fa-cogs"></i> SEO Setting</div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="title">Title</label>
                        <div class="col-md-9">
                            <?= $this->formText($page->get('title')) ?>
                            <?= $this->formElementErrors()->render($page->get('title'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="description">Meta Description</label>
                        <div class="col-md-9">
                            <?= $this->formTextarea($page->get('meta_description')) ?>
                            <?= $this->formElementErrors()->render($page->get('meta_description'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="keywords">Meta Keywords</label>
                        <div class="col-md-9">
                            <?= $this->formText($page->get('meta_keywords')) ?>
                            <?= $this->formElementErrors()->render($page->get('meta_keywords'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="keywords">Meta Robots</label>
                        <div class="col-md-9">
                            <?= $this->formSelect($page->get('meta_robots')) ?>
                            <?= $this->formElementErrors()->render($page->get('meta_robots'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading"><i class="fa fa-fw fa-cogs"></i> General Setting</div>
                <div class="panel-body">

                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Slug</label>
                            <?= $this->formText($page->get('page_slug')) ?>
                            <?= $this->formElementErrors()->render($page->get('page_slug'), ['class' => 'help-block']) ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <label for="status">Status</label>
                            <?= $this->formSelect($page->get('page_status')) ?>
                            <?= $this->formElementErrors()->render($page->get('page_status'), ['class' => 'help-block']) ?>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <?= $this->formButton($form->get('submit'), 'Save') ?>
                    <a href="<?= $this->url('page/delete', ['id' => $id], ['query' => ['redirect_url' => \urlencode($this->serverUrl(true))]]) ?>" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-o"></i> Delete</a>
                </div>
            </div>
        </div>
    </fieldset>
    <?php
    echo $this->formHidden($form->get('page_csrf'));
    echo $this->formHidden($page->get('user_id'));
    echo $this->formHidden($page->get('page_id'));
    echo $this->form()->closeTag()
    ?>
</div>