<?php
$this->headTitle('Do you want to delete this collection?');
?>
<div class="row">
    <div class="col-md-12">
        <legend><h2>Do you want to delete this collection?</h2></legend>
        <h4>Collection Info:</h4>
        <ul>
            <li>Name: <?= $collection->getCollectionName() ?></li>
            <li>ID: <?= $collection->getCollectionId() ?></li>
        </ul>

        <a class="btn btn-danger" href="<?= $this->url('collection/delete', ['id' => $id], ['query' => ['confirm' => 'yes', 'redirect_url' => $redirect_url]]) ?>">Yes</a>
        <a class="btn btn-default" href="<?= $this->url('collection/delete', ['id' => $id], ['query' => ['confirm' => 'no', 'redirect_url' => $redirect_url]]) ?>">No</a>
    </div>
</div>